FROM node:16.13.0-alpine

WORKDIR /workspace

COPY package.json .
RUN npm install --unsafe-perm

COPY . .

ENV API_URL=http://substra-backend.node-1.com:8000/

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080" ]
