FROM node:16.13.0-alpine

WORKDIR /workspace

ENV API_URL=backend:8000

COPY package.json .
RUN npm install --unsafe-perm

COPY src ./

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "8080" ]
