# Set the node version
FROM node:11.6.0

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY .babelrc /usr/src/app/.babelrc
COPY assets /usr/src/app/assets
COPY config /usr/src/app/config

COPY package-build.json /usr/src/app/package.json
COPY packages/ssr /usr/src/app/packages/ssr
COPY packages/base /usr/src/app/packages/base
COPY packages/plugins /usr/src/app/packages/plugins

COPY src /usr/src/app/src
COPY webpack /usr/src/app/webpack


RUN yarn install

# Build the production app

ENV NODE_ENV=production \
    NODE_PORT=8000 \
    SECURE_NODE_PORT=8443 \
    REDIS_PORT=6379

RUN yarn build:main

RUN rm -r /usr/src/app/src
RUN rm -r /usr/src/app/assets
COPY src/app/routesMap.js /usr/src/app/src/app/routesMap.js

EXPOSE $NODE_PORT $SECURE_NODE_PORT

CMD ["yarn", "serve"]
