apiVersion: skaffold/v1beta13
kind: Config
build:
  artifacts:
    - image: eu.gcr.io/substra-208412/substra-frontend
      context: .
      docker:
        target: build

deploy:
  helm:
    releases:
      - name: substra-frontend-peer-1
        chartPath: charts/substra-frontend
        namespace: peer-1
        imageStrategy:
          helm: {}
        values:
          image: eu.gcr.io/substra-208412/substra-frontend
        overrides:
          api:
            url: http://substra-backend.node-1.com
          ingress:
            enabled: true
            hosts:
              - { host: substra-frontend.node-1.com, paths: ["/"] }
            annotations:
              kubernetes.io/ingress.class: nginx

      - name: substra-frontend-peer-2
        chartPath: charts/substra-frontend
        namespace: peer-2
        imageStrategy:
          helm: {}
        values:
          image: eu.gcr.io/substra-208412/substra-frontend
        overrides:
          api:
            url: http://substra-backend.node-2.com
          ingress:
            enabled: true
            hosts:
              - { host: substra-frontend.node-2.com, paths: ["/"] }
            annotations:
              kubernetes.io/ingress.class: nginx
profiles:
  - name: dev
    patches:
      - op: add
        path: /build/artifacts/0/docker/dockerfile
        value: Dockerfile_dev
      - op: remove
        path: /build/artifacts/0/docker/target
      - op: add
        path: /build/artifacts/0/sync
        value:
            manual:
              - src: 'src/**/*'
                strip: 'src/'
                dest: /workspace/src
