apiVersion: skaffold/v2beta16
kind: Config
build:
    artifacts:
        - image: &imageref gcr.io/connect-314908/connect-frontend
          context: .
          docker:
              dockerfile: docker/connect-frontend/Dockerfile

deploy:
    helm:
        releases:
            - name: frontend-org-1
              chartPath: charts/connect-frontend
              namespace: org-1
              createNamespace: true
              artifactOverrides:
                  image: *imageref
              imageStrategy:
                  helm:
                      explicitRegistry: true
              valuesFiles:
                  - 'skaffold-values/org-1.yaml'

            - name: frontend-org-2
              chartPath: charts/connect-frontend
              namespace: org-2
              createNamespace: true
              artifactOverrides:
                  image: *imageref
              imageStrategy:
                  helm:
                      explicitRegistry: true
              valuesFiles:
                  - 'skaffold-values/org-2.yaml'

profiles:
    - name: single-org
      patches:
          - op: remove
            path: /deploy/helm/releases/1
