apiVersion: v1
name: substra-frontend
home: https://substra.org/
version: 1.0.0-alpha.3
description: Main package for Substra Frontend
icon: https://avatars1.githubusercontent.com/u/38098422?s=200&v=4
sources:
  - https://github.com/SubstraFoudation/substra-frontend
maintainers:
  - name: ClementGautier
    email: clement@gautier.im
