apiVersion: v2
name: substra-frontend
description: Frontend for Substra
icon: https://avatars.githubusercontent.com/u/84009910?s=400
keywords:
  - substra
sources:
  - https://github.com/Substra/substra-frontend

type: application

version: 1.0.8
appVersion: 0.36.0 # should be same as in package.json
kubeVersion: ">= 1.19.0-0"
