name: Build
# this workflow builds and pushes the "dev" versions of image and helm chart
# The versions are predictable:
#  helm: ci/version helm --insert-dev-info [--ref COMMIT_ID]
#  app: ci/version app --insert-dev-info [--ref COMMIT_ID]
#  docker: ci/version app tag --insert-dev-info [--ref COMMIT_ID]
#          (or just replacing + with _ in the app version, basically)
env:
    GCP_DOCKER_SERVER: gcr.io
# secrets:
#   GCP_SERVICE_ACCOUNT_KEY_JSON
#   HELM_REPO_USERNAME
#   HELM_REPO_PASSWORD
#   GH_PAT_USERNAME
#   GH_PAT
on:
    push:
        branches: [main]
    workflow_dispatch: {} # For running by hand from the web UI
jobs:
    build-image:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '>=3.9.0 <4.0.0'
            - run: python3 -m pip install -r ci/cilib/requirements.txt

            - run: printf '${{ secrets.GCP_SERVICE_ACCOUNT_KEY_JSON }}' | docker login -u _json_key --password-stdin https://$GCP_DOCKER_SERVER

            - run: ci/publish-docker --dev

    build-helm:
        name: Package Helm chart
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '>=3.9.0 <4.0.0'
            - run: python3 -m pip install -r ci/cilib/requirements.txt

            - run: helm lint charts/substra-frontend
            - run: helm package charts/substra-frontend
            - uses: actions/upload-artifact@v2
              with:
                  path: substra-frontend-*.tgz
                  if-no-files-found: error
            - run: ci/publish-helm '${{ secrets.HELM_REPO_USERNAME }}:${{ secrets.HELM_REPO_PASSWORD }}' --dev
