name: Hadolint
on:
    pull_request:
        paths:
            - 'docker/**'

jobs:
    lint:
        name: Lint Dockerfile
        runs-on: ubuntu-latest
        strategy:
            matrix:
                dockerfile:
                    - docker/substra-frontend/Dockerfile
                    - docker/substra-frontend-tests/Dockerfile
        steps:
            - uses: actions/checkout@v3
            - uses: hadolint/hadolint-action@v1.6.0
              with:
                  dockerfile: ${{ matrix.dockerfile }}
