name: Publish Helm
# This workflow builds the 'main' helm
# That is, any helm chart change that gets to main is immediately uploaded to the
# chart repo (that is to say it is released without further ado)
env: {}
on:
  push:
    branches:
      - "main"
    paths:
      - "charts/substra-frontend/**"
  pull_request:
    branches:
      - "main"
    paths:
      - "charts/substra-frontend/**"
  workflow_dispatch: {} # For running by hand from the web UI

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  helm:
    name: Helm
    uses: substra/substra-gha-workflows/.github/workflows/helm.yml@main
    with:
      helm-repositories: ''
    secrets: inherit
