name: Release
on:
    push:
        tags: ['*']
        # FYI this isn't triggered when more than 3 tags are pushed at once
        # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#push
env:
    REGISTRY: ghcr.io
jobs:
    issue-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - uses: docker/metadata-action@v5
              id: docker-metadata
              with:
                  images: 'ghcr.io/substra/substra-frontend'
                  tags: |
                      type=ref,event=tag
                      type=raw,value=latest

            - uses: docker/build-push-action@v5
              with:
                  push: ${{ github.event_name != 'pull_request' }}
                  file: ./docker/substra-frontend/Dockerfile
                  context: .
                  tags: ${{ steps.docker-metadata.outputs.tags }}
                  labels: ${{ steps.docker-metadata.outputs.labels }}
