name: Release
on:
    push:
        tags: ['*']
        # FYI this isn't triggered when more than 3 tags are pushed at once
        # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#push
env:
    REGISTRY: ghcr.io
# secrets:
#   HELM_REPO_USERNAME
#   HELM_REPO_PASSWORD
#   GH_PAT_USERNAME
#   GH_PAT
jobs:
    issue-release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: '>=3.9.0 <4.0.0'
            - run: python3 -m pip install -r ci/cilib/requirements.txt

            - uses: docker/login-action@v2
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            # github.ref should be of the form "refs/tags/0.6.0"
            - run: ci/publish-docker --tag "$( echo '${{ github.ref }}' | awk -F '/' '{print $3}')"
            # this will rebuild docker image, independantly of the continuous build workflow
