name: Validate PR
on:
    - pull_request

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.13.0'
            - name: Install node modules
              run: npm install
            - name: ESLint
              run: npm run eslint
            - name: Prettier
              run: npm run prettier
              # run this step even if the previous one failed
              if: always()
            - name: Typescript
              run: npx tsc
            - name: Deadcode
              run: npm run find-deadcode
            - name: Unused dependencies
              run: npm run find-unused-deps
            - name: Unit tests
              run: npm run test:unit
            - name: Helm
              run: helm lint charts/substra-frontend

    build: #separate for parallelization
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Docker
              run: DOCKER_BUILDKIT=1 docker build . -f docker/substra-frontend/Dockerfile
