name: Validate PR
on:
    - pull_request

jobs:
    validate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
            - uses: actions/setup-node@v2
              with:
                  node-version: '14.17.1'
            - name: Install node modules
              run: npm install
            - name: ESLint
              run: npm run eslint
            - name: Prettier
              run: npm run prettier
              # run this step even if the previous one failed
              if: always()
            - name: Typescript
              run: npx tsc
            - name: Unit tests
              run: npm run test:unit
